### ISSUE TITLE
problem  in kali Linux

### ISSUE THREAD

**Issue by msh50** [MetaChar/Hatch#1]
When used In kali Linux, what is the problem?

Traceback (most recent call last):
  File "main.py", line 16, in <module>
    driver = webdriver.Chrome()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.40,platform=Linux 4.18.0-kali2-amd64 x86_64)

**Comment by MetaChar** [comment]
Hi @msh50  did you install chromedriver & chrome if so is it the latest verion?

**Comment by msh50** [comment]
Thank you, username: msh#4591

**Comment by msh50** [comment]
I've tried it on Ubuntu it works well thank you

**Comment by miroschnichenkoMax** [comment]
Chrome(Chromium) won't run **as root!** You must run it as another user. 

Execute these only once:
**useradd -m kali
xhost +**

Then run the browser with:
**sudo -u kali python2 main.py**

**Comment by Caj6r** [comment]
i get this error on hatch when i run it on Kali. i have all the prerequisites and i have the chrome driver in my bin folder 
error:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from selenium import webdriver
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/__init__.py", line 21, in <module>
    from .chrome.webdriver import WebDriver as Chrome  # noqa
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 37
    """
    ^
IndentationError: unexpected indent

**Comment by Roor37734637647364** [comment]
raceback (most recent call last):
  File "main.py", line 122, in <module>
    driver = webdriver.Chrome()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home


plz help, I'm noob

**Comment by loemchetra** [comment]
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    driver = webdriver.Chrome()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home



please help me how to solve this problem?
I don't know how to do?

**Comment by shekhdaviraj** [comment]
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    driver = webdriver.Chrome()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error


Getting these problem.....
if anybody could help me out of these ??

**Comment by SLAYER7995** [comment]
> i get this error on hatch when i run it on Kali. i have all the prerequisites and i have the chrome driver in my bin folder
> error:
> 
> Traceback (most recent call last):
> File "main.py", line 9, in 
> from selenium import webdriver
> File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/**init**.py", line 21, in 
> from .chrome.webdriver import WebDriver as Chrome # noqa
> File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 37
> """
> ^
> IndentationError: unexpected indent

Did you find a fix yet?

**Comment by shekhdaviraj** [comment]
No dear but i got some idea that we need to install chrome browser and our
kali need 64 bit
