### ISSUE TITLE
ImportError: No module named common.exceptions

### ISSUE THREAD

**Issue by jayc12** [metachar/Hatch#12]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from selenium import webdriver
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/__init__.py", line 18, in <module>
    from .firefox.webdriver import WebDriver as Firefox  # noqa
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 29, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 26, in <module>
    from .webelement import WebElement
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 25, in <module>
    from selenium.common.exceptions import WebDriverException
ImportError: No module named common.exceptions

I can't seem to figure this issue out.
Please help.

**Comment by metachar** [comment]
https://stackoverflow.com/questions/49258228/importerror-no-module-named-common?rq=1
