### ISSUE TITLE
Chrome Drive Issue

### ISSUE THREAD

**Issue by MexMenuka** [metachar/Hatch#14]
python2 main.py 
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    driver = webdriver.Chrome()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by metachar** [comment]
https://github.com/heroku/heroku-buildpack-google-chrome/issues/46

"I wrote that error message. It means that ChromeDriver isn't finding the port it needs to talk to Chrome over. That could happen because Chrome crashed or failed to start or because you were using an old version of Chrome. ChromeDriver 2.40 only supports Chrome versions 66.x.x.x to 68.x.x.x.

It's also possible that it is failing because you are setting the "remote-debugging-port" argument. Could you try removing that argument?

See related bug https://bugs.chromium.org/p/chromedriver/issues/detail?id=2470&can=2&start=0&num=100&q=&colspec=ID%20Status%20Pri%20Owner%20Summary&groupby=&sort=&hotlist_id="
