### ISSUE TITLE
kali  error

### ISSUE THREAD

**Issue by Twuter** [MetaChar/Hatch#2]
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    display = Display(visible=1, size=(800, 800))  
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 52, in display_class
    cls.check_installed()
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/xephyr.py", line 30, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/local/lib/python2.7/dist-packages/easyprocess/__init__.py", line 182, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xephyr', '-help']
OSError=[Errno 2] No such file or directory
Program install error!

**Comment by MetaChar** [comment]
Sorry for the late response try 
```
sudo apt-get install xvfb
pip install xvfbwrapper
'''

**Comment by MetaChar** [comment]
I removed these from the script to fix this update to the newest version
