### ISSUE TITLE
Error in kali linux

### ISSUE THREAD

**Issue by Tofayel718** [metachar/Hatch#21]
When type 'python2 main.py' I get these errors.
I have installed latest chrome & chrome driver.
![Screenshot from 2019-10-13 06-19-05](https://user-images.githubusercontent.com/56486620/66705951-18748700-ed4f-11e9-9f9e-0d8c6f307fe3.png)
![Screenshot from 2019-10-13 06-19-05](https://user-images.githubusercontent.com/56486620/66705955-20342b80-ed4f-11e9-9528-f0ac1f666c5b.png)
![Screenshot from 2019-10-13 06-19-05](https://user-images.githubusercontent.com/56486620/66705961-2de9b100-ed4f-11e9-9b6b-2d2e8153dd71.png)

How can I fix it?
Thanks in advance!!!!
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    driver = webdriver.Chrome()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir

**Comment by sh1va73** [comment]
I have the same error.

**Comment by theharm-ful** [comment]
I am getting the same issue. please help

**Comment by cyber-kitten** [comment]
Have y’all tried it on windows that is the only current platform that supports this tool. I tried it on Ubuntu and Kali Linux and it won’t work. I watched a few tutorials cuz I thought maybe I was doing something wrong but apparently not. But try it on windows
