### ISSUE TITLE
how to solve this :)

### ISSUE THREAD

**Issue by mac23454** [metachar/Hatch#28]
root@kali:~/Desktop/Hatch# ls
 LICENSE  'logo (1).png'   main.py   passlist.txt   README.md
root@kali:~/Desktop/Hatch# python2 main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import selenium
ImportError: No module named selenium
root@kali:~/Desktop/Hatch#

**Comment by mac23454** [comment]
root@kali:~/Desktop/Hatch# python3 main.py
  File "main.py", line 97
    print '------------------------'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('------------------------')?
root@kali:~/Desktop/Hatch#

**Comment by c0d3gli7ch** [comment]
pip install selenium


> root@kali:~/Desktop/Hatch# python3 main.py File "main.py", line 97 print '------------------------' ^ SyntaxError: Missing parentheses in call to 'print'. Did you mean print('------------------------')? root@kali:~/Desktop/Hatch#

pip install selenium

**Comment by c0d3gli7ch** [comment]
> root@kali:~/Desktop/Hatch# ls LICENSE 'logo (1).png' main.py passlist.txt README.md root@kali:~/Desktop/Hatch# python2 main.py
> Traceback (most recent call last):
> File "main.py", line 5, in
> import selenium
> ImportError: No module named selenium
> root@kali:~/Desktop/Hatch#

pip install selenium
