### ISSUE TITLE
Error While Brute Force

### ISSUE THREAD

**Issue by jepunband** [MetaChar/Hatch#4]
AN ELEMENT HAS BEEN REMOVED FROM THE PAGE SOURCE THIS COULD MEAN 2 THINGS THE PASSWORD WAS FOUND OR YOU HAVE BEEN LOCKED OUT OF ATTEMPTS! 
LAST PASS ATTEMPT BELLOW
Traceback (most recent call last):
  File "main.py", line 136, in <module>
    wizard()
  File "main.py", line 75, in wizard
    brutes(username, username_selector ,password_selector,login_btn_selector,pass_list, website)
  File "main.py", line 107, in brutes
    print color.GREEN + 'Password has been found: {0}'.format(temp)
UnboundLocalError: local variable 'temp' referenced before assignment

**Comment by skyglider15** [comment]
try using python 2.7

**Comment by roboor** [comment]
This video watch and try it - https://youtu.be/A8WNA9oyDnk
