### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by mahimakamath** [MetaChar/Hatch#5]
**How can i fix it? after 40-50 Request the Hatch brakeing stop and send this fails in red.**

Traceback (most recent call last):
  File "main.py", line 132, in <module>
    wizard()
  File "main.py", line 74, in wizard
    brutes(username, username_selector ,password_selector,login_btn_selector,pass_list, website)
  File "main.py", line 87, in brutes
    browser.get(website)
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=72.0.3626.109)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.19.0-parrot1-13t-amd64 x86_64)

**Comment by MetaChar** [comment]
How many times has this happened?

**Comment by mahimakamath** [comment]
**hi, all time ;/ i though i fix it with** 
_Driver = webdriver.Chrome()
try:
    Driver.set_page_load_timeout(1)
    Driver.get("https://mapbase.siedler3.net/anmelden.html")
except TimeoutException as ex:
    isrunning = 0
    print("Exception has been thrown. " + str(ex))
    Driver.close()_
**today the following message, maybe the same i dont understand all of this output, it looks all time a little bit diffrent.**
  File "main.py", line 144, in <module>
    wizard()
  File "main.py", line 85, in wizard
    brutes(username, username_selector ,password_selector,login_btn_selector,pass_list, website)
  File "main.py", line 106, in brutes
    Sel_pas.send_keys(line)
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.141.0-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=72.0.3626.109)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.19.0-parrot1-13t-amd64 x86_64)
**thank you for you reply and help**

**Comment by roboor** [comment]
This video watch and try it - https://youtu.be/A8WNA9oyDnk
