### ISSUE TITLE
problem main.py

### ISSUE THREAD

**Issue by mcgregor10** [MetaChar/Hatch#8]
when i type in python2 main.py it says this        Traceback (most recent call last):
  File "mainelyly.py", line 122, in <module>
    driver = webdriver.Chrome()
  File "C:\Python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home     

what should i do i really want to try this

**Comment by zeeshan7860** [comment]
brother you need to put the chrmedriver executable in the python's path which is C:\Python27

**Comment by Roor37734637647364** [comment]
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    driver = webdriver.Chrome()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=73.0.3683.75,platform=Linux 4.19.0-kali4-amd64 x86_64)

Plz Help!

**Comment by mygitfile** [comment]
> brother you need to put the chrmedriver executable in the python's path which is C:\Python27

thanks bro

**Comment by thangeshbabu** [comment]
> brother you need to put the chrmedriver executable in the python's path which is C:\Python27

how to get in to that path

**Comment by roboor** [comment]
This video watch and try it - https://youtu.be/A8WNA9oyDnk
